// File generated by FlutterFire CLI.
// Questo file deve essere rigenerato con: flutterfire configure
// 
// Per ora usiamo placeholder - dovrai eseguire:
// dart pub global activate flutterfire_cli
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER - Sostituisci con le tue credenziali Firebase
  // Esegui: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMHwy0D4F4HWU5Nmg2pUrRqOdMRQZD3Q',
    appId: '1:1094661693162:android:7f68692c1a612c85868193',
    messagingSenderId: '1094661693162',
    projectId: 'splittycard',
    storageBucket: 'splittycard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgD_fWy7_HKIQVdMgEk5w3mWF0flRVqo',
    appId: '1:1094661693162:ios:5389972096d5e5c1868193',
    messagingSenderId: '1094661693162',
    projectId: 'splittycard',
    storageBucket: 'splittycard.firebasestorage.app',
    iosClientId: '1094661693162-l4s9skdehg96lna9l5420iu9uoeg00gj.apps.googleusercontent.com',
    iosBundleId: 'com.cardssplitter.cardsSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.cardssplitter.cardsSplitter',
  );
}


